sudo: required
language: go
go:
  - 1.6
services:
  - docker

before_install:
  - docker pull resin/raspberrypi3-golang
  - docker pull danielkun/go-docker-kubectl-arm32v7
  - docker pull danielkun/nginx-elm-raspbian-arm32v7
  - docker pull golang
  - docker pull danielkun/go-docker-kubectl-x86_64
  - docker pull danielkun/nginx-elm-debian-x86_64
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - wget -O manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 && chmod +x manifest-tool && sudo mv manifest-tool /usr/bin

script:
    - ./build/travis-make cross-build

after_success:
    - ./build/travis-make push

