apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: kube-alive
  name: getip-deployment
  labels:
    app: getip
spec:
  replicas: 4
  selector:
    matchLabels:
      app: getip
  template:
    metadata:
      namespace: kube-alive
      labels:
        app: getip
    spec:
      containers:
      - name: getip
        image: kubealive/getip
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  namespace: kube-alive
  name: getip
spec:
  selector:
    app: getip
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
